export const mockPapers = [
  {
    _id: 'paper-1',
    title: 'Retrieval-Augmented Reasoning for Domain-Specific Question Answering',
    topic: ['NLP'],
    summary:
      'This paper studies how retrieval-augmented pipelines improve factual accuracy in specialized question answering. It compares baseline generation with hybrid retrieval strategies and shows stronger answer grounding, especially in technical domains with sparse supervision.',
    audioUrl: '',
    pdfUrl: 'https://arxiv.org/pdf/2401.00001',
    views: 42,
    source: 'arXiv',
    externalId: '2401.00001',
    publishedAt: '2026-03-19T00:00:00.000Z',
    createdAt: '2026-03-20T00:00:00.000Z',
  },
  {
    _id: 'paper-2',
    title: 'Efficient Vision Encoders for Low-Latency Medical Image Screening',
    topic: ['Computer Vision'],
    summary:
      'The authors propose a compact vision encoder that preserves diagnostic quality while reducing inference time on edge devices. Their evaluation spans several medical imaging datasets and highlights a favorable balance between sensitivity, throughput, and deployment cost.',
    audioUrl: '',
    pdfUrl: 'https://arxiv.org/pdf/2402.00002',
    views: 28,
    source: 'arXiv',
    externalId: '2402.00002',
    publishedAt: '2026-02-11T00:00:00.000Z',
    createdAt: '2026-02-12T00:00:00.000Z',
  },
  {
    _id: 'paper-3',
    title: 'Curriculum-Based Reinforcement Learning for Long-Horizon Robotic Tasks',
    topic: ['Reinforcement Learning'],
    summary:
      'This work introduces a staged curriculum for robotic manipulation agents operating over long horizons. The reported gains come from progressive task decomposition, reward shaping constraints, and policy transfer between environments.',
    audioUrl: '',
    pdfUrl: 'https://arxiv.org/pdf/2403.00003',
    views: 35,
    source: 'arXiv',
    externalId: '2403.00003',
    publishedAt: '2026-01-22T00:00:00.000Z',
    createdAt: '2026-01-24T00:00:00.000Z',
  },
  {
    _id: 'paper-4',
    title: 'Multimodal Agents for Document Understanding and Action Planning',
    topic: ['NLP', 'Computer Vision'],
    summary:
      'The paper combines text reasoning and visual parsing to build agents that read dense documents, extract structured evidence, and generate action plans. Results suggest stronger performance on mixed-layout benchmarks and visually grounded decision tasks.',
    audioUrl: '',
    pdfUrl: 'https://arxiv.org/pdf/2404.00004',
    views: 51,
    source: 'arXiv',
    externalId: '2404.00004',
    publishedAt: '2026-04-02T00:00:00.000Z',
    createdAt: '2026-04-03T00:00:00.000Z',
  },
]
